model: fastdvdnet
dataset: loreal
loss: l2r

project_name: denoising-poisson-loreal-fastdvdnet-l2r
loreal_data_dir: /home/diegosilvera/Escritorio/2026/sequences_almost_Poisson
loreal_split_file: txts/loreal_split.txt

gamma: 0.00392156862745098   # 1/255
alpha: 0.15
l2r_eval_n_samples: 10
epochs: 150
batch_size: 32
val_batch_size: 32
lr: 0.0001
patch_size: 256
data_scale: 255.0
num_workers: 4
repeats_per_frame: 10
eval_seed: 43
checkpoint_every: 10
max_export_sequences: 2

val_prefixes: [HF1_, Mela1_]
test_prefixes: [HF2_, Mela2_]

pretrained_ckpt: FastDVDnet-pure_poisson-a=1-normalization_by_255.pth results/denoising-poisson-loreal-fastdvdnet-l2r/tif_output_2026_06_25-18_17_04/model_epoch20.pth #null #FastDVDnet-pure_poisson-a=1-normalization_by_255.pth
# inference_dir: null
# pretrained_ckpt: results/denoising-poisson-loreal-fastdvdnet-l2r/tif_output_2026_06_25-19_39_41/model_epoch50.pth
# inference_dir: results/denoising-poisson-loreal-fastdvdnet-l2r/tif_output_2026_06_25-19_39_41/results_epoch50

l2r_recorruptor_ckpt: /home/diegosilvera/Escritorio/learning2recorrupt/identity_recorruptor.pth
