model: drunet
dataset: loreal
loss: r2r

project_name: denoising-poisson-loreal-drunet
loreal_data_dir: /home/diegosilvera/Escritorio/2026/sequences_almost_Poisson
loreal_split_file: txts/loreal_split.txt

gamma: 0.00392156862745098   # 1/255
alpha: 0.15
epochs: 80
batch_size: 16
val_batch_size: 16
lr: 0.0001
patch_size: 256
data_scale: 255.0
num_workers: 4
repeats_per_frame: 10
eval_seed: 43
checkpoint_every: 10
max_export_sequences: 2

val_prefixes: [HF1_, Mela1_]
test_prefixes: [HF2_, Mela2_]

# Transfer learning from FMDD — update path to your best FMDD DRUNet checkpoint
pretrained_ckpt: results/denoising-poisson-fmdd-drunet/tif_output_2026_06_02-19_42_17/best_model.pth
inference_dir: null
