
import os
import sys
import torch
from pathlib import Path
from torch.utils.data import DataLoader
import numpy as np
from torchvision import transforms
import matplotlib.pyplot as plt

# Setup paths to import from deepinv and Lorentzian dataset
BASE_DIR = Path("/home/diegosilvera/Escritorio/GeneralizedR2R")
DEEPINV_PATH = BASE_DIR / "GeneralizedR2R" / "deepinv"
LOREAL_PATH = BASE_DIR.parent / "Loreal"

sys.path.append(str(DEEPINV_PATH))
sys.path.append(str(LOREAL_PATH))

import deepinv as dinv
from loreal_dataset_fixed import FMDDDataset, get_fmdd_sequences

def get_stats(loader, name):
    print(f"\nStats for {name}:")
    batch = next(iter(loader))
    if isinstance(batch, (list, tuple)):
        # Deepinv returns (x, y)
        x, y = batch
    else:
        x = batch
        y = None
    
    print(f"  Batch shape (y): {y.shape if y is not None else x.shape}")
    print(f"  Range (y): [{y.min().item():.4f}, {y.max().item():.4f}]" if y is not None else f"  Range (x): [{x.min().item():.4f}, {x.max().item():.4f}]")
    print(f"  Mean (y): {y.mean().item():.4f}" if y is not None else f"  Mean (x): {x.mean().item():.4f}")
    print(f"  Total batches: {len(loader)}")
    return x, y

def visualize():
    # 1. Setup for demo4poisson_modified4FMDD_goodresults.py style
    noise_level = 1/255.0
    noise_model = dinv.physics.PoissonNoise(noise_level)
    physics = dinv.physics.Denoising(noise_model=noise_model)
    
    # We'll use the HDF5 dataset generated by the script if it exists
    h5_path = BASE_DIR / "../data/FMDD/measurements/fmd/Denoising_0.00392156862745098/fmd_poisson_full0.h5"
    if h5_path.exists():
        dataset_good = dinv.datasets.HDF5Dataset(path=str(h5_path), train=True)
        loader_good = DataLoader(dataset_good, batch_size=16, shuffle=True)
        x_good, y_good = get_stats(loader_good, "Good Results (HDF5)")
    else:
        print("HDF5 dataset not found. Skipping Good Results stats.")
        y_good = None

    # 2. Setup for demo_test_poisson_modified4FMDD.py style
    ORIGINAL_DATA_DIR = Path("/home/diegosilvera/Escritorio/data/FMDD")
    img_types = ['TwoPhoton_BPAE_R'] # Just one for speed
    sequences = get_fmdd_sequences(ORIGINAL_DATA_DIR, modalities=img_types)
    
    # Normalizing as in the modified script
    train_dataset_mod = FMDDDataset(sequence_info=sequences, patch_size=(128, 128), 
                                    mode='synthetic', gamma=1.0/noise_level, data_scale=1.0, 
                                    num_frames=1)
    loader_mod = DataLoader(train_dataset_mod, batch_size=16, shuffle=True)
    y_stack_mod, y_target_mod = get_stats(loader_mod, "Modified Script (FMDDDataset)")

    # Plotting
    fig, axes = plt.subplots(2, 2, figsize=(10, 10))
    
    if y_good is not None:
        axes[0, 0].imshow(y_good[0, 0].cpu().numpy(), cmap='gray')
        axes[0, 0].set_title("Good Results Noisy")
        axes[0, 1].imshow(x_good[0, 0].cpu().numpy(), cmap='gray')
        axes[0, 1].set_title("Good Results GT")
    
    axes[1, 0].imshow(y_stack_mod[0, 0].cpu().numpy(), cmap='gray')
    axes[1, 0].set_title("Modified Script Noisy")
    axes[1, 1].imshow(y_target_mod[0, 0].cpu().numpy(), cmap='gray')
    axes[1, 1].set_title("Modified Script GT")
    
    plt.tight_layout()
    plt.savefig("comparison.png")
    print("\nComparison image saved as comparison.png")

if __name__ == "__main__":
    visualize()
